### PR TITLE
Update New Relic library to 1.3.0

### PR DESCRIPTION
**Pull request by deepwell**
Update New Relic to the latest version.

### CODE REVIEW

**Comment by JamesMGreene** [comment]
This was superseded by PR #3, which changes the version matching to `1.x.x` in order to allow versioning up without continual releases of this wrapper package.

Unfortunately, we really need @andreioprisan to tag a new version in git and release a new version to Meteorite/Atmosphere in order to benefit from these changes via a normal consumer workflow.

**Comment by andreioprisan** [comment]
This should be all set now.

**Comment by JamesMGreene** [comment]
@andreioprisan: This essentially reverted the effects of PR #3 (which would get the latest `1.x.x` version of the "newrelic" Node module) and locked it back in at `1.3.0` (which is already old: the latest is `1.4.0`). :cry:

**Comment by deepwell** [comment]
Hi @JamesMGreene, I want my deployments to be consistent and 100% reproducible not matter when or how many times I do them. Therefore if this package is not tied to a specific version of the upstream newrelic library, then I can't guarantee consistency between deployments.

I think this is a clever idea for development and test, but I couldn't rely on this for production.

**Pull request merged**
